# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

warnings_are_errors: false
language: R
sudo: false
cache: packages
deploy:
  skip_cleanup: true

r_github_packages:
  - cran/survival
