source("common/env-kh.R")
source("common/generate-sample.R")
source("lasso/lasso-functions.R")
source("kknn/kknn-functions.R")

kknn.data.Actb <- kknnImputeGene("Actb")
lasso.data.Actb <- LASSO("Actb")
plotData <- data.frame(lasso.data.Actb$predicted, kknn.data.Actb$predicted)
names(plotData) <- c("lasso", "kknn")
ggplot(plotData, aes(x=lasso, y=kknn, color = lasso)) + geom_point() + geom_line(aes(y=lasso))
