library("glmnet")
library("kknn")
library("mpath")
library("randomForest")
library("Hmisc")
load("data/MixedSpecies.rdata")
source("R/mixedSpeciesLasso.R")
source("R/mixedSpeciesLassoNegbin.R")
source("R/kknn-functions.R")
source("R/mixedSpeciesKknn.R")
source("R/randomForest_function.R")
source("R/mixedSpeciesRandomForest.R")
source("R/mixedSpeciesImput.R")

msg <- mixedSpeciesGene(mixedSpecies1000)
save(msg, file="data/mixedSpeciesGene1000.rda")
print("genes done...")
msc <- mixedSpeciesCells(mixedSpecies1000)
save(msc, file="data/mixedSpeciesCells1000.rda")
print("cells over")
