library("glmnet")
library("kknn")
library("randomForest")
library("Hmisc")
library('methods')
load("data/treutlein2016.rdata")
source("R/lasso-functions.R")
source("R/kknn-functions.R")
source("R/randomForest_function.R")
source("R/dropoutSimulation.R")

stdexprcell <- simulateDropoutCells(expressionData = expr, dropoutPercentage = 0.3,n = 1)
save(stdexprcell, file="data/StandardizedExprCells.rda")
print("cells done...")
